### ISSUE TITLE
In the overview-features page, the feature detail page does not match the feature link.

### ISSUE THREAD

**Issue by DuanYuePeng** [jenkinsci/cucumber-reports-plugin#116]
Steps to reproduce:
1. Generate the cucumber report using Jenkins cucumber report plugin (Version 3.4.0) based on the attached json file. The json file is generated by cucumber-java v1.2.4.
2. View the cucumber report, as shown below.
![default](https://cloud.githubusercontent.com/assets/12404141/22722783/4d249506-edf4-11e6-947a-bee244bcbbee.png)
3. Click the link of the first feature, which is "个人用户注册"

Expected Result: Entering the feature detail page of "个人用户注册".
Actual Result: It goes into the third feature, which is "特惠短信提醒", as shown below.
![default](https://cloud.githubusercontent.com/assets/12404141/22722893/15febe7a-edf5-11e6-834a-65d2c211d2fc.png)

You can find the json file and the cucumber report in the attachments. Please help. Thank you very much!

[cucumber-html-reports.zip](https://github.com/damianszczepanik/cucumber-reporting-jenkins/files/759675/cucumber-html-reports.zip)
[cucumber-report-batch1.zip](https://github.com/damianszczepanik/cucumber-reporting-jenkins/files/759676/cucumber-report-batch1.zip)

**Comment by damianszczepanik** [comment]
The problem is that you have feature file named using no ASCII characters what is not forbidden but problematic if this goes to URI and needs to converted to file name that can be smoothly displayed by the browser.

So the problem is that URI from the feature file is converted quite naive by https://github.com/damianszczepanik/cucumber-reporting/blob/master/src/main/java/net/masterthought/cucumber/util/Util.java#L80

Can you suggest way how to convert it so it works not only for ASCII URI?

**Comment by damianszczepanik** [comment]
http://stackoverflow.com/a/34900072/2974624 seems to be promissing
