### ISSUE TITLE
Is there a way to set up the thresholds in percentage values ?

### ISSUE THREAD

**Issue by krish2304** [jenkinsci/cucumber-reports-plugin#204]
We have a requirement to fail the builds if the tests pass percentage is less than 80%. The cucumber reports plugin gives the option to make build stable or unstable based on the "no of steps". Is ther a way to set this threshold using percentage value ?

Thanks

**Comment by damianszczepanik** [comment]
It's not supported so far but looks like good idea

**Comment by gunesmes** [comment]
is there any improvement in this feature?

**Comment by Downright-Development** [comment]
I could be interested in helping with a PR. This sounds like a sweet idea. That being said, what would the business rules be as far as percentage? Would every configurable parameter have its own scale to 100? Does it default to 0? 0 bring if stuff fails who cares, 100 bring everything just pass?

**Comment by damianszczepanik** [comment]
@Downright-Development  that's a very good and important questions!
My must-have are: to be compatible with older version of the plugin and to be extensionable for the future request. The rest is open :)

**Comment by Downright-Development** [comment]
> @Downright-Development that's a very good and important questions!
> My must-have are: to be compatible with older version of the plugin and to be extensionable for the future request. The rest is open :)

I guess I could see this facilitated by an additional checkbox or something to toggle between base integers, and percentages. Otherwise you'd have to guess if "1" was a threshold of 1, or 1% of total steps/features/etc... Thoughts?

**Comment by damianszczepanik** [comment]
Then you suggest to implement new as xor while I'd like to have logic so then I have benefit of using both

**Comment by Downright-Development** [comment]
@damianszczepanik Are you suggesting benefit of using both types within one build? Hmm, interesting point. Perhaps it can constrained a bit:

- Is there a benefit of only allowing whole percentages (flooring their say... 6.8% to 6%)? I say this because in either the percentage, or in the amount of steps passing compared to the total, you'll need a whole number. Personally, I like the idea of flooring their 6.8% to 6% better than dealing with the math on the other end (i.e you can't have 26.5 steps passing, it's either 26, or 27).
- Can you supply "1" and "1%" to the same threshold? Sounds silly to me, but if both were provided, would one supersede over the other? 
- How could you see allowing the user to provide "1" to field A, and "6%" to field B? Should it be configurable per field with some sort of ticker box? Or should the plugin require that the user enters the "%" sign, and that's the switching logic? (i.e. the code would handle 6% as a real percentage, rather than a threshold of the integer 6)

Would love to hear feedback :) Also, if I were to tackle this PR where you suggest looking first?

**Comment by damianszczepanik** [comment]
As the SQA leader
I want to fail the report if the most 2 tests fail but not more than 5% of all
So then some unstable features don't make the whole report failed.

**Comment by Downright-Development** [comment]
> As the SQA leader
> I want to fail the report if the most 2 tests fail but not more than 5% of all
> So then some unstable features don't make the whole report failed.

Hmm, so you're suggesting you'd like to use "2" and "5%" within one field such as number failed scenarios?

**Comment by damianszczepanik** [comment]
Rather 'or'

**Comment by damianszczepanik** [comment]
Rather 'or'

**Comment by thiagotrentin** [comment]
Hi @damianszczepanik, this feature will fit perfectly with my need
are you planning to implement this?

> As the SQA leader
> I want to fail the report if the most 2 tests fail but not more than 5% of all
> So then some unstable features don't make the whole report failed.

**Comment by damianszczepanik** [comment]
Yes but without specified deadline. Do you want to prepare PR about this?

**Comment by thiagotrentin** [comment]
> Yes but without specified deadline. Do you want to prepare PR about this?

yes, I'll try to do it, but it's my first plugin improvement, so if you have some advice, it will help me.

**Comment by damianszczepanik** [comment]
Recommend to search for the commit that enables to decide about build status and prepare similar for percentage.

**Comment by damianszczepanik** [comment]
Will be delivered with next release

**Comment by Mr-H** [comment]
Please can you provide an example of how to implement the percentage thresholds. If you can provide guidance, we are happy to test it as an early adopter.

**Comment by damianszczepanik** [comment]
Upgrade the plugin, documentation is provided within the plugin as usually.
