### ISSUE TITLE
CSS inline error with reports

### ISSUE THREAD

**Issue by anadimisra** [jenkinsci/cucumber-reports-plugin#7]
Hi! 

We get the following error when viewing these reports on either Firefox or chrome

Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-e3PTf-8JkKrhRPBrS7V8Iocbz9X5jIld6OXpK8Cbo2Y='), or a nonce ('nonce-...') is required to enable inline execution.

![arrrgh](https://cloud.githubusercontent.com/assets/1317613/11899685/d4c32a8a-a5c6-11e5-8058-97d0d6b66f1d.png)

Stackoverflow points to some operations done in iframe or replace calls on DOM elements, kind of picking it up as an XSS attack.

**Comment by idealivan** [comment]
I've encountered the same error like this one. More, I was reported that another problem like below:
Blocked script execution in 'http://x.x.x.x:8080/job/cucumber-sample/cucumber-html-reports/step-overview.html' because the document's frame is sandboxed and the 'allow-scripts' permission is not set.

Any one has idea about solving these problems?

Thanks

**Comment by vietch2612** [comment]
Same problem here!

**Comment by damianszczepanik** [comment]
I understand that the problem exist but I can't reproduce it

**Comment by idealivan** [comment]
Hi Damian, what kind of help you may need to reproduce this error. What I know is that I access the report provided by my Jenkins server via IP address and server port is not 80 but 8080.  If you need more information, reply me.

**Comment by damianszczepanik** [comment]
My Chrome and Firefox don't complain about such issue.  Report is displayed as usually

**Comment by idealivan** [comment]
Damian, I had sent you an email, I had an online environment in which you can recreate this issue.

**Comment by damianszczepanik** [comment]
I need to reproduce it locally otherwise I won't be able to check if patch works or not.

**Comment by idealivan** [comment]
I may help try the fix work or not when it is ready.

**Comment by idealivan** [comment]
Try this URL to recreat this issue: http://52.68.4.130:8080/job/cucumber-sample/cucumber-html-reports/

**Comment by damianszczepanik** [comment]
Ok i think that the problem is with json file you have. Attach json report so I will try generate report locally

**Comment by idealivan** [comment]
http://52.68.4.130:8080/job/cucumber-sample/ws/target/json-report/applications.json

**Comment by idealivan** [comment]
Here you have the jaon report!

**Comment by damianszczepanik** [comment]
Thanks I will check it soon

**Comment by idealivan** [comment]
There are Chinese characters in the report, with utf8 encoding to make sure the json is correctly displayed.

**Comment by damianszczepanik** [comment]
Ok, I see that problem happens after upgrading Jenkins to newer version and is also reported in damianszczepanik/cucumber-reporting-jenkins/issues/152

As a quick patch I can recommend to downgrade Jenkins. I will try to fix it but since there are many violations it may take a little bit

**Comment by damianszczepanik** [comment]
As long as plugin contains resources such as css or JS you need to configure Jenkins according to this guide https://wiki.jenkins-ci.org/display/JENKINS/Configuring+Content+Security+Policy

**Comment by idealivan** [comment]
The solution works on my site, thanks Damian for the quick solution!

**Comment by anadimisra** [comment]
Tried an overtly liberal 

 ```
hudson.model.DirectoryBrowserSupport.CSP = "default-src 'none'; img-src 'self'; style-src 'self' 'unsafe-inline'; child-src 'self'; frame-src 'self';"
```
But I still get the same error. any other quick hacks that might be helpful?

**Comment by jglick** [comment]
> As long as plugin contains resources such as css or JS you need to configure Jenkins according to this guide

No! That is a _short-term workaround_ which restores the security vulnerability, to be used only in cases where the plugin maintainer cannot fix the issue.

The fix needs to be made in this plugin. You may use `DirectoryBrowserSupport` on files  which the user's build generated. You should not use it on files which the plugin generates, unless those are vanilla HTML. If you need to render any kind of potentially dangerous content, you must do that directly from plugin views on demand, without loading potentially tainted user content.

**Comment by daniel-beck** [comment]
> to be used only in cases where the plugin maintainer cannot fix the issue.

Well, in all fairness, many Jenkins instances will not need the kind of protection provided by CSP, and IMO it's perfectly fine for them to disable it. It really depends on the specific use case and threat model.

That said, plugins can make adjustments to make things work reasonably well when files aren't served from the workspace/archive/similar build-related directories. In this case, it seems to require an adjustment in the report generator to not use inline CSS, but external CSS files. (Graphs which AFAIU are either prohibited JS or prohibited Flash will still be broken though.)

> You should not use it on files which the plugin generates, unless those are vanilla HTML.

The caveat here is that plugin generated files stored in the build folder will still be susceptible to later modifications. So even if the plugin generates the file, and stores it outside the workspace and archived artifacts with the build, they could be tampered with later.

**Comment by daniel-beck** [comment]
From what I can tell by looking at the plugin, it seems that it would actually be an improvement -- independent of the CSP issue -- if the report was generated on the fly based on archived JSON files. Generation options like Flash vs. JavaScript graphs could be applied to past reports as well, and future improvements to the report UI could be applied to existing reports. This doesn't even mention the waste of disk space (1.8MB for a very basic report for a 1.5KB JSON file) caused by the current approach to generate static files.

Of course this would require a rather large overhaul of the plugin as far as I can tell, and wouldn't actually fix existing reports, but it looks like a possible way forward in a major update that both restores compatibility with the default Content Security Policy (while that may get tweaked, it is very unlikely to ever allow any `object-src` or `script-src` out of the box) and improves the plugin overall.

@damianszczepanik If this is something you'd consider, feel free to contact me for help.

**Comment by damianszczepanik** [comment]
@daniel-beck I'd rather not want to make big refactor now but I would be happy if you provide example (code reference) how to fix this problem

**Comment by daniel-beck** [comment]
@damianszczepanik It really depends on the plugin how to best approach this. So far, I provided patches to:

* HTML Publisher: https://github.com/jenkinsci/htmlpublisher-plugin/pull/22
* Javadoc Plugin: https://github.com/jenkinsci/javadoc-plugin/pull/4

HTML Publisher serves the wrapper frame HTML file using a Groovy view that just pipes it through if its checksum matches what was archived with the build. Backwards compatibility is ensured by checking the wrapper file contents for sanity if there's no checksum (builds created before the plugin was updated).

Javadoc plugin is a partial fix that basically makes the frameless index file the default, rather than the frame. There's just too many files, with (probably) too much user control over their content to handle this a different way in my opinion. Luckily, the Javadoc sites I tested worked fine even with their minimal JS blocked.

I had a different approach to HTML Publisher prepared as well, which was basically an entire overhaul of the plugin: Only archive the necessary metadata, and then serve an ad-hoc generated wrapper frame based on its contents. This was a rather large diff, and still had a backward compatibility problem, so I opted for the smaller change linked to above. Since your plugin starts out with the metadata and generates the site based on that, I doubt this would be of help, but I can publish this if you're interested.

Other plugins are hopeless and just need users to reduce the CSP level. The Maven site publishing in Maven Plugin, for example, or all the users who publish sites using the core Archive Artifacts functionality. But I don't think your plugin falls into this category.

I'd be happy to look into this further if you'd be willing to accept a PR in principle.

**Comment by damianszczepanik** [comment]
I will, thank you!

**Comment by FrankZZ** [comment]
+1

**Comment by imakowski** [comment]
When fix will be delivered?

**Comment by vasidzius** [comment]
The same issue

**Comment by damianszczepanik** [comment]
Will be released with next version

**Comment by enggabhishekshinde** [comment]
Please do following steps to fix it.

Add or modify following parameter in /etc/sysconfig/jenkins file..

JENKINS_JAVA_OPTIONS=" -Djava.awt.headless=true -Dhudson.model.DirectoryBrowserSupport.CSP=\"\" "

**Comment by HerrmannHinz** [comment]
@enggabhishekshinde thanks this worked like a charm

**Comment by josephzilberman** [comment]
JAVA_ARGS="${JAVA_ARGS} -Djava.awt.headless=true -Dhudson.model.DirectoryBrowserSupport.CSP=\"\" "

**Comment by damianszczepanik** [comment]
I recommend plugin upgrade over security workaround...

**Comment by sakshisood** [comment]
I have tried setting in tomcat file but it does not work at all

#JENKINS_JAVA_OPTIONS="-Dhudson.model.DirectoryBrowserSupport.CSP=\"default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline';\" -Djenkins.model.DirectoryBrowserSupport.CSP=\"default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline';\""

#JAVA_ARGS="$JAVA_ARGS -Dhudson.model.DirectoryBrowserSupport.CSP=\"default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline';\" -Djenkins.model.DirectoryBrowserSupport.CSP=\"default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline';\""


Please help its blocking me

**Comment by enggabhishekshinde** [comment]
HI sakshisood,

pass empty parameter in JENKINS_JAVA_OPTIONS.

JENKINS_JAVA_OPTIONS=" -Djava.awt.headless=true -Dhudson.model.DirectoryBrowserSupport.CSP="""

or

JAVA_ARGS="${JAVA_ARGS} -Djava.awt.headless=true -Dhudson.model.DirectoryBrowserSupport.CSP="" "

Regards,
Abhi.
