### ISSUE TITLE
Jenkins Base Path stopped working in latest plugin version 3.1.0

### ISSUE THREAD

**Issue by LuckySpb** [jenkinsci/cucumber-reports-plugin#91]
Plugin property Jenkins Base Path is ignored in some links in cucumber JVM reports tab.
Links: Jenkins, Previous results, Latest results - are incorrectly pointing to root hostname
Links: Features, Tags, Steps, Trends, Failures - are correctly pointing to "Jenkins Base Path" property
Here "Jenkins Base Path" is configured to http://hostname:8080/jenkins
![cucumber-jvm-reports_jenkins_base_path](https://cloud.githubusercontent.com/assets/1247214/19521237/e784e202-95e0-11e6-9623-e660de9f87b1.png)

**Comment by yermulnik** [comment]
Experiencing same issue here. Jenkins ver. 2.7.3

**Comment by damianszczepanik** [comment]
This happens when you up ply major update an you are trying to open old report from new one

**Comment by LuckySpb** [comment]
Nope.
This happens for last generated reports as well

I think issue is in last appendix "/../" to jenkins path
http://hostname:8080/jenkins2**/../**

New items like "Features" don't specify absolute path in "a-href" explicitly, so they are resolved correctly automatically

` <ul class="nav navbar-nav navbar-right">
	<li role="presentation"><a href="http://hostname:8080/jenkins2/../">Jenkins</a></li>
    <li role="presentation"><a href="http://hostname:8080/jenkins2/../../72/cucumber-html-reports/overview-features.html">Previous results</a></li>
    <li role="presentation"><a href="http://hostname:8080/jenkins2/../../lastBuild/cucumber-html-reports/overview-features.html">Latest results</a></li>
    <li role="presentation"  class="active" ><a href="overview-features.html">Features</a></li>
    <li role="presentation" ><a href="overview-tags.html">Tags</a></li>
    <li role="presentation" ><a href="overview-steps.html">Steps</a></li>
    <li role="presentation" ><a href="overview-trends.html">Trends</a></li>
    <li role="presentation" ><a href="overview-failures.html">Failures</a></li>
</ul>
`

**Comment by yermulnik** [comment]
> This happens when you up ply major update an you are trying to open old report from new one
It happens on fresh plugin install and tests generation.

**Comment by damianszczepanik** [comment]
OK guys, I see the problem so let me understand how it should be fixed. Let me know the answer for following questions so this Base Path can be implemented correctly. The logic of this hasn't been changed from a while so if you raise the problem about this that means that there is no many users that defined this property.

1. What is the reason you want to define such properly and what is the value of this?
2. What is the proper link to the last Feature Overview page (use the link with "lastBuild" that points to the last build without the number of this build).
3. What is the proper link to the previous Feature Overview (use build number such as http://hostname:8080/job/myJob/23/... )
4. What happens when you leave Base Path empty?

**Comment by LuckySpb** [comment]
1. In previous versions of plugin if my jenkins is not on the root domain, but has some context
(like http://hostname:8080/jenkins instead http://hostname:8080/) then Top Level links were pointing to
hostname:8080/job instead of hostname:8080/jenkins/job and led to 404 error.
(last installed version was 2.2.0, but base path might have been configured even earlier)
2. proper link
http://hostname:8080/jenkins/view/view-name/job/job-name/74/cucumber-html-reports/overview-features.html
3. Can't find it. Seems with new version plugin does not give "Cucumber-JVM reports" link for old builds
4. It works =)

I think issue that I described in point 1 is already fixed, you are using relative path instead of absolute domain and this property is not required anymore

**Comment by damianszczepanik** [comment]
Thanks for letting me know - that was very helpful!

@yermulnik what is your answer?

**Comment by yermulnik** [comment]
Sorry for delay — it was night over here =)

1. My Jenkins is behind the Application Load Balancer and is accessible only by its URI. So I followed plugin's wiki and defined its URI. It's: `/jenkins/build01/`
2. `https://hostname/jenkins/build01/job/POC/job/job-name/lastBuild/cucumber-html-reports/overview-features.html`
3. It's only one build since plugin installation. So here's its URL: `https://hostname/jenkins/build01/job/POC/job/job-name/4/cucumber-html-reports/overview-features.html`
4. It works! Links are correct =)
